Remove inexistent alias which provoked a PHP error
Fixes:

Fatal error: An alias (traitPreRender) was defined for method
preRender(), but this method does not exist in
/var/www/html/modules/elasticsearch_connector/modules/elasticsearch_connector_views/src/Plugin/views/field/ElasticsearchViewsEntityField.php
on line 21

See
https://circleci.com/gh/juampynr/elasticsearch_connector/47#artifacts/containers/0